apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vinay-negative-full-proxy 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vv_negative_proxy_test
        tier: backend
        track: stable
    spec:
      containers:
        - name: vinay-centos-2-app
          image: "vinayvenkat/vv_centos_net_utils"
          command: ["python"]
          args: ["-m", "SimpleHTTPServer", "80"]
      initContainers:
        - name: init-proxy
          image: vinayvenkat/vv_init_proxy
          command: ['/home/init_iptables.sh']
          args: ["-p", "15001", "-u", "1337"]
          imagePullPolicy: "IfNotPresent"
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
