apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vinay-proxy-client-test 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vv_proxy_client_test
        tier: backend
        track: stable
    spec:
      containers:
        - name: vv-proxy-listener
          image: "vinayvenkat/vv_centos_net_utils"
          command: ["socat"]
          args: ["-v","TCP4-LISTEN:15001,reuseaddr,fork", "TCP4:10.244.2.57:80"]
          ports:
            - name: http
              containerPort: 15001
        - name: vinay-centos-2-app
          image: "vinayvenkat/vv_centos_net_utils"
          command: ["python"]
          args: ["-m", "SimpleHTTPServer", "81"]
      initContainers:
        - name: init-proxy
          image: vinayvenkat/vv_init_proxy
          command: ['/home/init_iptables.sh']
          args: ["-p", "15001", "-u", "1337"]
          imagePullPolicy: "Always"
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
