apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: exp-deployment
  labels:
    app: expapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expapp
  template:
    metadata:
      labels:
        app: expapp
    spec:
      containers:
      - name: expapp
        image: vinayvenkat/priv_exploit_v2
