apiVersion: "v1"
kind: Pod
metadata:
  name: test
  labels:
    name: test
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: nginx
          protocol: TCP
    - name: alpine
      image: alpine
      command: ['sleep']
      args: ['15m']
